function [assigments] = kmeanscompare(matrix, partitions)
    assigments = arrayfun(@(k) kmeans(matrix, k), ...
        1:max(max(partitions)), ...
        'UniformOutput', false);
    assigments = cell2mat(assigments)';
end
