function [assigments] = kmeanscompare(matrix, partitions)
    assigments = arrayfun(@(k) kmeans(matrix, max(partitions(k, :))), ...
        1:size(partitions, 1), ...
        'UniformOutput', false);
    assigments = cell2mat(assigments)';
end
